import type { GamepadData } from "../hooks/useGamepad";

export const joyConMappings = {
  0: "b",
  1: "a",
  2: "y",
  3: "x",
  4: "L",
  5: "R",
  6: "zl",
  7: "zr",
  8: "MINUS",
  9: "PLUS",
  10: "L3",
  11: "R3",
  12: "UP",
  13: "DOWN",
  14: "LEFT",
  15: "RIGHT",
  16: "HOME",
  17: "CAMERA",
  18: "SL-LEFT",
  19: "SR-LEFT",
  20: "SL-RIGHT",
  21: "SR-RIGHT",
  b: 0,
  a: 1,
  y: 2,
  x: 3,
  L: 4,
  R: 5,
  zl: 6,
  zr: 7,
  MINUS: 8,
  PLUS: 9,
  L3: 10,
  R3: 11,
  UP: 12,
  DOWN: 13,
  LEFT: 14,
  RIGHT: 15,
  HOME: 16,
  CAMERA: 17,
  "SL-LEFT": 18,
  "SR-LEFT": 19,
  "SL-RIGHT": 20,
  "SR-RIGHT": 21,
};

const agnosticControllerSpiral = {
  LEFT_STICK_DOWN: 0,
  LEFT_STICK_LEFT: 1,
  LEFT_STICK_UP: 2,
  LEFT_STICK_RIGHT: 3,
  DPAD_DOWN: 4,
  DPAD_LEFT: 5,
  DPAD_UP: 6,
  DPAD_RIGHT: 7,
  BUTTON_BOTTOM: 8,
  BUTTON_LEFT: 9,
  BUTTON_TOP: 10,
  BUTTON_RIGHT: 11,
  LEFT_BUMPER: 12,
  LEFT_TRIGGER: 13,
  RIGHT_BUMPER: 14,
  RIGHT_TRIGGER: 15,
  RIGHT_STICK_DOWN: 16,
  RIGHT_STICK_LEFT: 17,
  RIGHT_STICK_UP: 18,
  RIGHT_STICK_RIGHT: 19,
  SELECT: 20,
  START: 21,
  L3: 22,
  R3: 23,
  MYSTERY_1: 24,
  MYSTERY_2: 25,
  MYSTERY_3: 26,
  MYSTERY_4: 27,
  HOME: 28,
  SHARE_OR_CAMERA: 29,
};

//@ts-ignore
const agnosticControllerInterlacedSpiral = {
  LEFT_STICK_DOWN: 0,
  LEFT_STICK_LEFT: 2,
  LEFT_STICK_UP: 4,
  LEFT_STICK_RIGHT: 6,
  DPAD_DOWN: 8,
  DPAD_LEFT: 10,
  DPAD_UP: 12,
  DPAD_RIGHT: 14,
  BUTTON_BOTTOM: 9,
  BUTTON_LEFT: 11,
  BUTTON_TOP: 13,
  BUTTON_RIGHT: 15,
  LEFT_BUMPER: 16,
  LEFT_TRIGGER: 18,
  RIGHT_BUMPER: 17,
  RIGHT_TRIGGER: 19,
  RIGHT_STICK_DOWN: 1,
  RIGHT_STICK_LEFT: 3,
  RIGHT_STICK_UP: 5,
  RIGHT_STICK_RIGHT: 7,
  SELECT: 20,
  START: 21,
};

export const agnosticController = agnosticControllerSpiral;

export const joyConToAgnosticMappings = {
  b: agnosticController.BUTTON_BOTTOM,
  a: agnosticController.BUTTON_RIGHT,
  y: agnosticController.BUTTON_LEFT,
  x: agnosticController.BUTTON_TOP,
  DOWN: agnosticController.DPAD_DOWN,
  LEFT: agnosticController.DPAD_LEFT,
  RIGHT: agnosticController.DPAD_RIGHT,
  UP: agnosticController.DPAD_UP,
  L: agnosticController.LEFT_BUMPER,
  zl: agnosticController.LEFT_TRIGGER,
  zr: agnosticController.RIGHT_TRIGGER,
  R: agnosticController.RIGHT_BUMPER,
  MINUS: agnosticController.SELECT,
  PLUS: agnosticController.START,
  L3: agnosticController.L3,
  R3: agnosticController.R3,
  "SL-LEFT": agnosticController.MYSTERY_1,
  "SR-LEFT": agnosticController.MYSTERY_2,
  "SL-RIGHT": agnosticController.MYSTERY_3,
  "SR-RIGHT": agnosticController.MYSTERY_4,
  HOME: agnosticController.HOME,
  CAMERA: agnosticController.SHARE_OR_CAMERA,
};

export const xboxToAgnosticMappings = {
  A: agnosticController.BUTTON_BOTTOM,
  B: agnosticController.BUTTON_RIGHT,
  X: agnosticController.BUTTON_LEFT,
  Y: agnosticController.BUTTON_TOP,
  LB: agnosticController.LEFT_BUMPER,
  RB: agnosticController.RIGHT_BUMPER,
  LT: agnosticController.LEFT_TRIGGER,
  RT: agnosticController.RIGHT_TRIGGER,
  VIEW: agnosticController.SELECT,
  MENU: agnosticController.START,
  L3: agnosticController.L3,
  R3: agnosticController.R3,
  UP: agnosticController.DPAD_UP,
  DOWN: agnosticController.DPAD_DOWN,
  LEFT: agnosticController.DPAD_LEFT,
  RIGHT: agnosticController.DPAD_RIGHT,
  XBOX: agnosticController.HOME,
};

export const xboxControllerMappings = {
  0: "A",
  1: "B",
  2: "X",
  3: "Y",
  4: "LB",
  5: "RB",
  6: "LT",
  7: "RT",
  8: "VIEW",
  9: "MENU",
  10: "L3",
  11: "R3",
  12: "UP",
  13: "DOWN",
  14: "LEFT",
  15: "RIGHT",
  16: "XBOX",
  A: 0,
  B: 1,
  X: 2,
  Y: 3,
  LB: 4,
  RB: 5,
  LT: 6,
  RT: 7,
  VIEW: 8,
  MENU: 9,
  L3: 10,
  R3: 11,
  LEFT: 14,
  DOWN: 13,
  UP: 12,
  RIGHT: 15,
  XBOX: 16,
};

export const playstationControllerMappings = {
  0: "CROSS",
  1: "CIRCLE",
  2: "SQUARE",
  3: "TRIANGLE",
  4: "L1",
  5: "R1",
  6: "L2",
  7: "R2",
  8: "SHARE",
  9: "OPTIONS",
  10: "L3",
  11: "R3",
  12: "UP",
  13: "DOWN",
  14: "LEFT",
  15: "RIGHT",
  16: "PS",
  17: "TOUCHPAD",
  CROSS: 0,
  CIRCLE: 1,
  SQUARE: 2,
  TRIANGLE: 3,
  L1: 4,
  R1: 5,
  L2: 6,
  R2: 7,
  SHARE: 8,
  OPTIONS: 9,
  L3: 10,
  R3: 11,
  UP: 12,
  DOWN: 13,
  LEFT: 14,
  RIGHT: 15,
  PS: 16,
  TOUCHPAD: 17,
};

export const playstationToAgnosticMappings = {
  CROSS: agnosticController.BUTTON_BOTTOM,
  CIRCLE: agnosticController.BUTTON_RIGHT,
  SQUARE: agnosticController.BUTTON_LEFT,
  TRIANGLE: agnosticController.BUTTON_TOP,
  L1: agnosticController.LEFT_BUMPER,
  R1: agnosticController.RIGHT_BUMPER,
  L2: agnosticController.LEFT_TRIGGER,
  R2: agnosticController.RIGHT_TRIGGER,
  SHARE: agnosticController.SHARE_OR_CAMERA,
  OPTIONS: agnosticController.SELECT,
  L3: agnosticController.L3,
  R3: agnosticController.R3,
  UP: agnosticController.DPAD_UP,
  DOWN: agnosticController.DPAD_DOWN,
  LEFT: agnosticController.DPAD_LEFT,
  RIGHT: agnosticController.DPAD_RIGHT,
  PS: agnosticController.HOME,
  TOUCHPAD: agnosticController.SHARE_OR_CAMERA,
};

export function detectGamepadType(gamepad: Gamepad): GamepadData["type"] {
  let t: GamepadData["type"] = "unknown";
  if (gamepad.id.toLowerCase().includes("joy")) {
    t = "joycon";
  } else if (gamepad.id.toLowerCase().includes("xbox")) {
    t = "xbox";
  } else if (gamepad.id.toLowerCase().includes("playstation")) {
    t = "playstation";
  }
  return t;
}
