export const joyConMappings = {
  0: "b",
  1: "a",
  2: "y",
  3: "x",
  4: "L",
  5: "R",
  6: "zl",
  7: "zr",
  8: "MINUS",
  9: "PLUS",
  10: "L3",
  11: "R3",
  12: "UP",
  13: "DOWN",
  14: "LEFT",
  15: "RIGHT",
  16: "HOME",
  17: "CAMERA",
  18: "SL-LEFT",
  19: "SR-LEFT",
  20: "SL-RIGHT",
  21: "SR-RIGHT",
  b: 0,
  a: 1,
  y: 2,
  x: 3,
  L: 4,
  R: 5,
  zl: 6,
  zr: 7,
  MINUS: 8,
  PLUS: 9,
  L3: 10,
  R3: 11,
  UP: 12,
  DOWN: 13,
  LEFT: 14,
  RIGHT: 15,
  HOME: 16,
  CAMERA: 17,
  "SL-LEFT": 18,
  "SR-LEFT": 19,
  "SL-RIGHT": 20,
  "SR-RIGHT": 21,
};

const agnosticControllerSpiral = {
  LEFT_STICK_DOWN: 0,
  LEFT_STICK_LEFT: 1,
  LEFT_STICK_UP: 2,
  LEFT_STICK_RIGHT: 3,
  DPAD_DOWN: 4,
  DPAD_LEFT: 5,
  DPAD_UP: 6,
  DPAD_RIGHT: 7,
  BUTTON_BOTTOM: 8,
  BUTTON_LEFT: 9,
  BUTTON_TOP: 10,
  BUTTON_RIGHT: 11,
  LEFT_BUMPER: 12,
  LEFT_TRIGGER: 13,
  RIGHT_BUMPER: 14,
  RIGHT_TRIGGER: 15,
  RIGHT_STICK_DOWN: 16,
  RIGHT_STICK_LEFT: 17,
  RIGHT_STICK_UP: 18,
  RIGHT_STICK_RIGHT: 19,
  SELECT: 20,
  START: 21,
};

//@ts-ignore
const agnosticControllerInterlacedSpiral = {
  LEFT_STICK_DOWN: 0,
  LEFT_STICK_LEFT: 2,
  LEFT_STICK_UP: 4,
  LEFT_STICK_RIGHT: 6,
  DPAD_DOWN: 8,
  DPAD_LEFT: 10,
  DPAD_UP: 12,
  DPAD_RIGHT: 14,
  BUTTON_BOTTOM: 9,
  BUTTON_LEFT: 11,
  BUTTON_TOP: 13,
  BUTTON_RIGHT: 15,
  LEFT_BUMPER: 16,
  LEFT_TRIGGER: 18,
  RIGHT_BUMPER: 17,
  RIGHT_TRIGGER: 19,
  RIGHT_STICK_DOWN: 1,
  RIGHT_STICK_LEFT: 3,
  RIGHT_STICK_UP: 5,
  RIGHT_STICK_RIGHT: 7,
  SELECT: 20,
  START: 21,
};

export const agnosticController = agnosticControllerSpiral;

export const joyConToAgnosticMappings = {
  b: agnosticController.BUTTON_BOTTOM,
  a: agnosticController.BUTTON_RIGHT,
  y: agnosticController.BUTTON_LEFT,
  x: agnosticController.BUTTON_TOP,
  DOWN: agnosticController.DPAD_DOWN,
  LEFT: agnosticController.DPAD_LEFT,
  RIGHT: agnosticController.DPAD_RIGHT,
  UP: agnosticController.DPAD_UP,
  L: agnosticController.LEFT_BUMPER,
  zl: agnosticController.LEFT_TRIGGER,
  zr: agnosticController.RIGHT_TRIGGER,
  R: agnosticController.RIGHT_BUMPER,
  MINUS: agnosticController.SELECT,
  PLUS: agnosticController.START,
};

export const xboxControllerMappings = {
  0: "A",
  1: "B",
  2: "Y",
  3: "X",
  4: "LB",
  5: "RB",
  6: "LT",
  7: "RT",
  8: "VIEW",
  9: "MENU",
  10: "L3",
  11: "R3",
  12: "LEFT",
  13: "DOWN",
  14: "UP",
  15: "RIGHT",
  16: "HOME",
  A: 0,
  B: 1,
  Y: 2,
  X: 3,
  LB: 4,
  RB: 5,
  LT: 6,
  RT: 7,
  VIEW: 8,
  MENU: 9,
  L3: 10,
  R3: 11,
  LEFT: 12,
  DOWN: 13,
  UP: 14,
  RIGHT: 15,
  HOME: 16,
};
